name: Build Hyprland on debian

on:
  workflow_dispatch:

jobs:
  hyprland-arm64:
    name: Build package on arm64
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout Hyprland
        uses: actions/checkout@v3
        with:
          repository: hyprwm/Hyprland
          path: Hyprland
          ref: v0.27.0
          submodules: recursive

      - name: Running build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          #base_image: arm64v8/r-base
          base_image: --platform=linux/arm64 debian:bookworm
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"

          # env: | # YAML, but pipe character is necessary
          #   DESTDIR: /artifacts

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          install: |
            echo "deb-src http://deb.debian.org/debian/ bookworm contrib main non-free non-free-firmware" >> /etc/apt/sources.list

            apt-get update -q -y > /dev/null

            apt-get install -q -y git jq build-essential ninja-build meson hwdata libcairo2-dev libpango1.0-dev wget cmake-extras \
            cmake gettext gettext-base fontconfig libfontconfig-dev libffi-dev libxml2-dev libdrm-dev libxkbcommon-x11-dev libxkbregistry-dev \
            libxkbcommon-dev libpixman-1-dev libudev-dev libseat-dev seatd libxcb-dri3-dev libvulkan-dev libvulkan-volk-dev  vulkan-validationlayers-dev \
            libvkfft-dev libgulkan-dev libegl-dev libgles2 libegl1-mesa-dev glslang-tools libinput-bin libinput-dev libxcb-composite0-dev libavutil-dev \
            libavcodec-dev libavformat-dev libxcb-ewmh2 libxcb-ewmh-dev libxcb-present-dev libxcb-icccm4-dev libxcb-render-util0-dev libxcb-res0-dev libxcb-xinput-dev xdg-desktop-portal-wlr > /dev/null

            apt-get build-dep wlroots -q -y > /dev/null
            apt-get build-dep wayland -q -y > /dev/null

          run: |
            git clone https://gitlab.freedesktop.org/wayland/wayland --quiet
            cd wayland
            meson build/ --prefix=/artifacts/usr
            ninja -C build/ install
            cd ..
            cd Hyprland
            cd subprojects
            git clone https://gitlab.freedesktop.org/emersion/libdisplay-info --quiet
            git clone https://github.com/emersion/libliftoff --quiet
            cd ..
            meson build --prefix=/artifacts/usr
            ninja -C build
            ninja -C build install

      - name: Packaging the build
        run: |
          tar -cvf hyprland.tar ${PWD}/artifacts/usr

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hyprland_debian
          path: hyprland.tar
