name: Build linux kernel for chromebook kukui

on:
  workflow_dispatch:

jobs:
  kukui-arm64:
    name: Build kernel on arm64
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@v1
        with:
          PKGBUILD: linux-kukui/PKGBUILD

      - name: List
        run: |
          ~/arch-packages

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-kukui
          path: ~/arch-packages/*
