name: Build linux kernel for chromebook kukui

on:
  workflow_dispatch:

jobs:
  kukui-arm64:
    name: Build kernel on arm64
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Create user
        run: |
          pacman -Sy sudo --noconfirm
          useradd -m user || true
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S base-devel --noconfirm

      - name: Build Package
        run: |
          chown -R user:user linux-kukui
          su - user
          cd linux-kukui
          mkdir result
          CARCH=aarch64 PKGDEST=result makepkg -s --noconfirm

      - name: List
        run: |
          result

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-kukui
          path: result/*
