name: Build LLVM

on:
  workflow_dispatch:

jobs:
  llvm-debian:
    name: Build package on arm64
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout llvm
        run: git clone --recursive -b 17 https://salsa.debian.org/pkg-llvm-team/llvm-toolchain.git

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(TZ='Asia/Singapore' /bin/date "+%I:%M%p_%d/%m/%Y")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Mkdir
        run: |
          sudo rm -rf /var/cache/pbuilder/ccache
          install -d -m 2775 -o 1234 -g 1234 /var/cache/pbuilder/ccache
          echo 'for i in $(echo {0..9}) $(echo {a..f}) tmp; do mkdir -p /var/cache/pbuilder/ccache/$i; done' | bash
          chown -R 1234:1234 /var/cache/pbuilder/ccache

      - name: ccache cache files
        uses: actions/cache/restore@v3
        with:
          path: /var/cache/pbuilder/ccache
          key: llvm-bookworm-arm64-ccache-

      - name: Install deps
        run: |
          export DEBIAN_FRONTEND=noninteractive
          git config --global http.postBuffer 157286400
          echo "deb-src http://deb.debian.org/debian/ bookworm contrib main non-free non-free-firmware" > /etc/apt/sources.list
          apt-get update && apt-get install -q -y \
          git build-essential apt-utils git-buildpackage dh-autoreconf quilt dh-ocaml time libz3-dev cowbuilder \
          && rm -rf /var/lib/apt/lists/*

          sudo cat <<EOF > "/etc/pbuilderrc"
          export CCACHE_DIR="/var/cache/pbuilder/ccache"
          export PATH="/usr/lib/ccache:${PATH}"
          EXTRAPACKAGES="ccache"
          BINDMOUNTS="${CCACHE_DIR}"
          EOF
          
          rm -rf /var/cache/pbuilder/*.cow
          DIST=bookworm git-pbuilder create --mirror http://deb.debian.org/debian
          echo "apt-mark hold hello hello-traditional && chown -R 1234:1234 /var/cache/pbuilder/ccache" > command.sh
          cowbuilder execute --basepath /var/cache/pbuilder/base-bookworm.cow --distribution bookworm --save-after-exec -- ./command.sh

      - name: Build
        run: |
          sh llvm-toolchain/debian/orig-tar.sh 17.0.6
          cd llvm-toolchain
          gbp buildpackage --git-upstream-tree="17" --git-upstream-signatures=off --git-ignore-new --git-ignore-branch --git-pbuilder --git-dist=bookworm -i -us -uc -b
          cd ..
          ls -lah

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: /var/cache/pbuilder/ccache
          key: llvm-bookworm-arm64-ccache-${{ steps.get-date.outputs.date }}

      - name: Move to debian repo
        run: |
          rm -rf *dbgsym*.deb
          cp *.deb debian/pool

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: List GPG keys
        run: gpg -K

      - name: Write new package to repo
        run: |
          cd $GITHUB_WORKSPACE/debian
          rm Packages || echo "Failed to remove packages file"
          rm Packages.gz || echo "Failed to remove packages.gz file"
          rm Release || echo "Failed to remove release file"
          rm Release.gpg || echo "Failed to remove release.gpg file"
          rm InRelease || echo "Failed to remove inrelease file"
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          gpg --default-key LesVu -abs -o - Release > Release.gpg || error "failed to sign Release.gpg with gpg "
          gpg --default-key LesVu --clearsign -o - Release > InRelease || error "failed to sign InRelease with gpg"

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "debian/*"

      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: llvm
          path: ./*.deb
