name: Build Neovim

on:
  workflow_dispatch:

jobs:
  neovim-debian:
    name: Build package on arm64
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout Neovim
        uses: actions/checkout@v3
        with:
          repository: neovim/neovim
          path: neovim
          ref: stable

      - name: Running build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          #base_image: arm64v8/r-base
          base_image: --platform=linux/arm64 debian:bookworm
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"

          env: | # YAML, but pipe character is necessary
            DESTDIR: /artifacts

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          install: |
            apt-get update -q -y > /dev/null

            apt-get install -q -y git jq build-essential libunibilium-dev ninja-build gettext cmake unzip software-properties-common curl > /dev/null

          run: |
            cd neovim
            make deps
            make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_FLAGS="-D CI_BUILD=ON"
            cd build
            cpack -G DEB
            mv *.deb /artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nvim_debian
          path: artifacts/*.deb
