name: Build Neovim

on:
  workflow_dispatch:

jobs:
  neovim-debian:
    name: Build package on arm64
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout Neovim
        uses: actions/checkout@v3
        with:
          repository: neovim/neovim
          path: neovim
          ref: stable

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Mkdir
        run: mkdir -p "${PWD}/ccache"

      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path: ccache
          key: neovim_arm64-ccache-${{ steps.get-date.outputs.date }}
          restore-keys: |
            neovim_arm64-ccache-

      - name: Running build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          #base_image: arm64v8/r-base
          base_image: --platform=linux/arm64 debian:bookworm
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"

          env: | # YAML, but pipe character is necessary
            DESTDIR: /artifacts

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            --volume "${PWD}/ccache:/root/.ccache"

          install: |
            apt-get update -q -y > /dev/null

            apt-get install -q -y git jq build-essential ccache libtool-bin tar unzip ninja-build gettext cmake unzip software-properties-common curl libunibilium-dev > /dev/null

          run: |
            cd neovim
            make NVIM_BUILD_TYPE=Release CMAKE_BUILD_TYPE=Release
            cd build
            cpack -G DEB
            mv *.deb /artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nvim_debian
          path: artifacts/*.deb
